---

antora:
  name: modules
  dir: www
  modules:
  - name: module-01
    label: Manipulating File Contents
    solveButton: true
  - name: module-02
    label: Viewing the end of log files with 'tail'
  - name: module-03
    label: Locating Files
  - name: module-04
    label: Searching for text within files and outputs
  - name: module-05
    label: Using 'df' to check disk usage
  - name: module-06
    label: Viewing processes
  - name: module-07
    label: Using 'free' to view information about the system memory usage

tabs:
- name: ">_ rhel"
  url: /wetty
- name: ">_ root"
  url: /wetty
  user: root
